<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Оформление заказа");
$APPLICATION->SetTitle("Оформление заказа");
?>
<div class="container">
	<div id ="content" class="row">
		
<?$APPLICATION->IncludeComponent(
	"bitrix:sale.order.ajax", 
	"v2_custom", 
	[
		"COMPONENT_TEMPLATE" => "v2_custom",
		"PAY_FROM_ACCOUNT" => "N",
		"ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
		"ALLOW_AUTO_REGISTER" => "Y",
		"ALLOW_APPEND_ORDER" => "Y",
		"SEND_NEW_USER_NOTIFY" => "N",
		"DELIVERY_NO_AJAX" => "N",
		"SHOW_NOT_CALCULATED_DELIVERIES" => "L",
		"DELIVERY_NO_SESSION" => "Y",
		"TEMPLATE_LOCATION" => "popup",
		"SPOT_LOCATION_BY_GEOIP" => "Y",
		"DELIVERY_TO_PAYSYSTEM" => "d2p",
		"SHOW_VAT_PRICE" => "N",
		"USE_PREPAYMENT" => "N",
		"COMPATIBLE_MODE" => "Y",
		"USE_PRELOAD" => "N",
		"ALLOW_USER_PROFILES" => "N",
		"ALLOW_NEW_PROFILE" => "N",
		"TEMPLATE_THEME" => "site",
		"SHOW_ORDER_BUTTON" => "final_step",
		"SHOW_TOTAL_ORDER_BUTTON" => "N",
		"SHOW_PAY_SYSTEM_LIST_NAMES" => "N",
		"SHOW_PAY_SYSTEM_INFO_NAME" => "N",
		"SHOW_DELIVERY_LIST_NAMES" => "N",
		"SHOW_DELIVERY_INFO_NAME" => "N",
		"SHOW_DELIVERY_PARENT_NAMES" => "N",
		"SHOW_STORES_IMAGES" => "N",
		"SKIP_USELESS_BLOCK" => "Y",
		"BASKET_POSITION" => "before",
		"SHOW_BASKET_HEADERS" => "Y",
		"DELIVERY_FADE_EXTRA_SERVICES" => "N",
		"SHOW_NEAREST_PICKUP" => "N",
		"DELIVERIES_PER_PAGE" => "1",
		"PAY_SYSTEMS_PER_PAGE" => "1",
		"PICKUPS_PER_PAGE" => "1",
		"SHOW_PICKUP_MAP" => "N",
		"SHOW_MAP_IN_PROPS" => "N",
		"PICKUP_MAP_TYPE" => "yandex",
		"SHOW_COUPONS" => "N",
		"SHOW_COUPONS_BASKET" => "N",
		"SHOW_COUPONS_DELIVERY" => "N",
		"SHOW_COUPONS_PAY_SYSTEM" => "Y",
		"USER_CONSENT" => "Y",
		"USER_CONSENT_ID" => "1",
		"USER_CONSENT_IS_CHECKED" => "N",
		"USER_CONSENT_IS_LOADED" => "N",
		"ACTION_VARIABLE" => "soa-action",
		"PATH_TO_BASKET" => "/personal/cart/",
		"PATH_TO_PERSONAL" => "/personal/",
		"PATH_TO_PAYMENT" => "payment.php",
		"PATH_TO_AUTH" => "/auth/",
		"SET_TITLE" => "Y",
		"DISABLE_BASKET_REDIRECT" => "N",
		"EMPTY_BASKET_HINT_PATH" => "/",
		"USE_PHONE_NORMALIZATION" => "Y",
		"PRODUCT_COLUMNS_VISIBLE" => [
			0 => "PREVIEW_PICTURE",
			1 => "PROPS",
			2 => "PROPERTY_ARTICLE",
		],
		"ADDITIONAL_PICT_PROP_1" => "MORE_PHOTO",
		"ADDITIONAL_PICT_PROP_2" => "-",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"SERVICES_IMAGES_SCALING" => "adaptive",
		"PRODUCT_COLUMNS_HIDDEN" => [
		],
		"HIDE_ORDER_DESCRIPTION" => "Y",
		"USE_YM_GOALS" => "Y",
		"USE_ENHANCED_ECOMMERCE" => "Y",
		"USE_CUSTOM_MAIN_MESSAGES" => "N",
		"USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
		"USE_CUSTOM_ERROR_MESSAGES" => "N",
		"PROPS_FADE_LIST_1" => [
		],
		"YM_GOALS_COUNTER" => "100102212",
		"YM_GOALS_INITIALIZE" => "",
		"YM_GOALS_EDIT_REGION" => "",
		"YM_GOALS_EDIT_DELIVERY" => "",
		"YM_GOALS_EDIT_PICKUP" => "",
		"YM_GOALS_EDIT_PAY_SYSTEM" => "",
		"YM_GOALS_EDIT_PROPERTIES" => "",
		"YM_GOALS_EDIT_BASKET" => "",
		"YM_GOALS_NEXT_REGION" => "",
		"YM_GOALS_NEXT_DELIVERY" => "",
		"YM_GOALS_NEXT_PICKUP" => "",
		"YM_GOALS_NEXT_PAY_SYSTEM" => "",
		"YM_GOALS_NEXT_PROPERTIES" => "",
		"YM_GOALS_NEXT_BASKET" => "",
		"YM_GOALS_SAVE_ORDER" => "order",
		"DATA_LAYER_NAME" => "dataLayer",
		"BRAND_PROPERTY" => ""
	],
	false
);?>
</div>
</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>